apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
spec:
  selector:
    replicas: 2
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: lbrunoq/gitops:latest
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 3000
