apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

images:
- name: goserver
  newName: lbrunoq/gitops
  newTag: d9945e991fd2cd66dc73bfd49a5881019c46a139
